import { FOR_AGE } from "../data/for-age";

const evidence = [
  {
    label: "Real data",
    value: "3 trees · 6 clouds",
    copy: "Three Lillomarka trees are shipped as paired ALSHD / MLS browser samples derived from FOR-age."
  },
  {
    label: "Source-derived labels",
    value: "69–223 years",
    copy: "The showcased specimens preserve dataset age, species, height, crown measurements, acquisition modality, and split."
  },
  {
    label: "Reproducible pipeline",
    value: "≤100k points / cloud",
    copy: "Browser assets are deterministic XYZ derivatives generated by an open preprocessing script and traceable to the dataset DOI."
  }
] as const;

export function PrototypeEvidencePanel() {
  return (
    <section className="evidencePanel" aria-labelledby="evidence-title">
      <div className="evidenceIntro">
        <p className="eyebrow">What is live now</p>
        <h2 id="evidence-title">A small real-data slice, end to end.</h2>
        <p>
          This release deliberately keeps the scope narrow: real public forest geometry,
          inspectable metadata, reproducible processing, and source-backed research context.
        </p>
      </div>

      <div className="evidenceGrid">
        {evidence.map((item) => (
          <article key={item.label}>
            <span>{item.label}</span>
            <strong>{item.value}</strong>
            <p>{item.copy}</p>
          </article>
        ))}
      </div>

      <div className="evidenceSource">
        <span>Dataset anchor</span>
        <a href={FOR_AGE.zenodoUrl} target="_blank" rel="noreferrer">
          FOR-age · DOI {FOR_AGE.doi} ↗
        </a>
      </div>
    </section>
  );
}
